version = 1

[[annotations]]
path = "assembly/*.jpg"
SPDX-FileCopyrightText = "2025 Hackropole"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "firmware-wled/*.bin"
SPDX-FileCopyrightText = "2016-present Christian Schwinne and individual WLED contributors"
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = "firmware-wled/wled_led_settings.png"
SPDX-FileCopyrightText = "2025 Hackropole"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "hardware/*.kicad_*"
SPDX-FileCopyrightText = "2025 Hackropole"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "hardware/fp-lib-table"
SPDX-FileCopyrightText = "2025 Hackropole"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "hardware/sym-lib-table"
SPDX-FileCopyrightText = "2025 Hackropole"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "hardware/*.jpg"
SPDX-FileCopyrightText = "2025 Hackropole"
SPDX-License-Identifier = "CC-BY-4.0"
